# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ssh-matrix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: setup
        run: |
          sudo tailscale up --authkey=tskey-auth-ktSKUb6psG11CNTRL-DoLqRmZ3duDY8GYc6dvGvDTtja5ogvgb --hostname=gha-$(curl -s ifconfig.io) --accept-routes

      - name: status
        run: |
          while true; do
            date
            tailscale status --peers=false | head -n 5
            sleep 5
          done
          
